### ISSUE TITLE
Please support Inserts a upgrade-insecure-request to https response in order to resolve some common MCB.

### ISSUE THREAD

**Issue by ivysrono** [ilGur1132/Smart-HTTPS#3]
We need [UpgradeMixedContent](https://github.com/gloomy-ghost/UpgradeMixedContent) now.

**Comment by mrdokenny** [comment]
That extension complements well with Smart-HTTPS so I combined both of them in ea12641c21d3cf24e7dc888ea75af449ab7784d6 (so I install only one extension and not two).

Feel free to use the [fork](https://github.com/mrdokenny/Smart-HTTPS/releases) until the developer adds this.
